version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.3.0
    steps:
      - checkout
      - run: node --version
      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn